package backend.todo.todobackend.controller;


import backend.todo.todobackend.entity.Priority;
import backend.todo.todobackend.service.PriorityService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;


@RestController
@RequestMapping("/priority") // base URI
public class PriorityController {


    private PriorityService priorityService;

    public PriorityController(PriorityService priorityService) {
        this.priorityService = priorityService;
    }


    //fetch all priorities by email
    @PostMapping("/all")
    public List<Priority> findAll(@RequestBody String email) {

        return priorityService.findAll(email);
    }

    @PostMapping("/add")
    public ResponseEntity<Priority> add(@RequestBody Priority priority) {

        // check required parameters
        if (priority.getId() != null && priority.getId() != 0) {
            // id is autogenerated in DB (autoincrement), so it should not be passed, otherwise unique constraint conflicts may occur
            return new ResponseEntity("redundant param: id MUST be null", HttpStatus.NOT_ACCEPTABLE);
        }

        // if title is empty
        if (priority.getTitle() == null || priority.getTitle().trim().length() == 0) {
            return new ResponseEntity("missed param: title", HttpStatus.NOT_ACCEPTABLE);
        }

        // if color is empty
        if (priority.getColor() == null || priority.getColor().trim().length() == 0) {
            return new ResponseEntity("missed param: color", HttpStatus.NOT_ACCEPTABLE);
        }

        // save works for both create and update
        return ResponseEntity.ok(priorityService.add(priority));
    }


    //Add endpoint to update priority with validation
    @PutMapping("/update")
    public ResponseEntity update(@RequestBody Priority priority) {

        // check required parameters
        if (priority.getId() == null || priority.getId() == 0) {
            return new ResponseEntity("missed param: id", HttpStatus.NOT_ACCEPTABLE);
        }

        // if title is empty
        if (priority.getTitle() == null || priority.getTitle().trim().length() == 0) {
            return new ResponseEntity("missed param: title", HttpStatus.NOT_ACCEPTABLE);
        }

        // if color is empty
        if (priority.getColor() == null || priority.getColor().trim().length() == 0) {
            return new ResponseEntity("missed param: color", HttpStatus.NOT_ACCEPTABLE);
        }

        // save works for both create and update
        priorityService.update(priority);

        return new ResponseEntity(HttpStatus.OK); // just return status 200 (operation successful)
    }


}
